default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres # Use your macOS username
  password: password  # Optional, depending on your setup
  host: localhost
  port: 5432

development:
  <<: *default
  database: open_mic_2_0_development

test:
  <<: *default
  database: open_mic_2_0_test

production:
  <<: *default
  database: open_mic_2_0_production
  username: open_mic_2_0
  password: <%= ENV['OPEN_MIC_DATABASE_PASSWORD'] %>
